### ISSUE TITLE
why always open terminal when start the output binary

### ISSUE THREAD

**Issue by yifan513** [huckor/wxwidgets-vscode#11]
As the title. 
why always open terminal when start the output binary? Is there any setting to avoid that?
Thanks
David

**Comment by huckor** [comment]
I'm not sure what exactly you are facing on your machine so could you elaborate?
On my machine there is running terminal inside VCS but just for compilation and linking processes. When actual application starts then terminal is not running anymore.
Terminal has to start because all compilation and linking tasks are executed inside it. But still this terminal is running as part of VSC.

**Comment by huckor** [comment]
No response for few months - closing this thread.
