### ISSUE TITLE
fatal error: 'wx/setup.h' file not found

### ISSUE THREAD

**Issue by oq-x** [huckor/wxwidgets-vscode#12]
![image](https://github.com/huckor/wxwidgets-vscode/assets/84847714/975c9a6f-e61b-4086-bb1a-73578d1fa081)

**Comment by huckor** [comment]
According your error it seems you did not properly follow instructions [HowTo compile static wxWidgets library for macOS using 64bit gcc compiler](https://github.com/huckor/wxwidgets-vscode/blob/master/doc/mac.pdf).
Configuration failed because MacOS SDK was not found.
![253776259-975c9a6f-e61b-4086-bb1a-73578d1fa081](https://github.com/huckor/wxwidgets-vscode/assets/20068605/2795e823-5ffb-429f-aaf2-016cbc6e44f6)
